### ISSUE TITLE
Invalid JSON Response from API

### ISSUE THREAD

**Issue by TrioxSecure** [Yankue/easy-roblox-api#2]
FetchError {message: 'invalid json response body at https://users.roblox… reason: Unexpected token ﻿ in JSON at position 0', type: 'invalid-json', stack: 'FetchError: invalid json response body at https://…\\node_modules\\easy-roblox-api\\src\\getUser.js:8:34'}message: "invalid json response body at https://users.roblox.com/v1/users/156/status reason: Unexpected token ﻿ in JSON at position 0"type: "invalid-json"stack: "FetchError: invalid json response body at https://users.roblox.com/v1/users/156/status reason: Unexpected token ﻿ in JSON at position 0\n    at C:\\Users\\haide\\Documents\\bloxstation-desktop\\node_modules\\node-fetch\\lib\\index.js:273:32\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async C:\\Users\\haide\\Documents\\bloxstation-desktop\\node_modules\\easy-roblox-api\\src\\getUser.js:8:34"[[Prototype]]: Error

**Comment by Yankue** [comment]
Hey, is it possible for me to see the code you're running thats giving this error?

**Comment by TrioxSecure** [comment]
roblox.getUser("builderman", "username").then(response => {
   console.log(response); 
}).catch(() => {
  console.log("An error occured, most likely that user does't exist!");
});

using this in a node js based electron desktop app

i got this error in the console log{
FetchError {message: 'invalid json response body at https://users.roblox… reason: Unexpected token ﻿ in JSON at position 0', type: 'invalid-json', stack: 'FetchError: invalid json response body at https://…\\node_modules\\easy-roblox-api\\src\\getUser.js:8:34'}

}

**Comment by Yankue** [comment]
This was a bug I found and have now fixed. It was a simple fix, the library hasn't been updated since Roblox removed the status feature, so that was giving us a Roblox API error. Sorry this bug occured, have a good day!
